apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Nginx Application</title>
    </head>
    <body>
        <h1>Welcome to My Nginx Application!</h1>
    </body>
    </html>
