apiVersion: v1
kind: Pod
metadata:
  name: python-server-pod
spec:
  containers:
  - name: python-server
    image: python:3.8
    command: ["python", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
